import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub,
} from "react-icons/ai";
import pfp from "../../public/pfp.png";
import Image from "next/image";
import Card from "./components/card";
import AwardCard from "./components/awardcard";
import { motion } from "framer-motion";
import { useState } from "react";
import { TypeAnimation } from "react-type-animation";
import { SocialIcon } from "react-social-icons";

export default function Home() {
  return (
    <motion.div
      initial={{ opacity: 0 }}
      transition={{ duration: 2 }}
      animate={{ opacity: 1 }}
    >
      <div>
        <html className="scroll-smooth">
          <Head>
            <title>Meor&apos;s Web Portfolio</title>
            <meta name="description" content="Generated by create next app" />
            <meta
              name="viewport"
              content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <main className=" bg-black px-10">
            <section className="min-h-screen">
              <nav className="py-4 mb-12 flex justify-between">
                <motion.h1
                  initial={{ opacity: 0, x: -50 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ duration: 1.5 }}
                  className="text-xl p-10 "
                >
                  developedbymeor
                </motion.h1>
                <ul className="flex items-center">
                  <li className="px-1">
                    <SocialIcon
                      url="https://twitter.com/MeorSyamil"
                      bgColor="transparent"
                      fgColor="grey"
                    />
                  </li>
                  <li className="px-1">
                    <SocialIcon
                      url="https://www.facebook.com/meor.syamil/"
                      bgColor="transparent"
                      fgColor="grey"
                    />
                  </li>
                  <li className="px-1">
                    <SocialIcon
                      url="https://www.linkedin.com/in/meor-syamil-59935a153/"
                      bgColor="transparent"
                      fgColor="grey"
                    />
                  </li>
                  <li className="px-1">
                    <SocialIcon
                      url="https://github.com/w30r"
                      bgColor="transparent"
                      fgColor="grey"
                    />
                  </li>
                </ul>
              </nav>
              <div className="text-center flex items-center flex-col ">
                <motion.div
                  initial={{ scale: 1.1 }}
                  animate={{ scale: 1 }}
                  transition={{
                    duration: 3,
                    repeat: Infinity,
                    repeatType: "reverse",
                  }}
                  className="mb-12 relative bg-gradient-to-b via-cyan-900 from-teal-600 to-black rounded-full w-60 h-60 mx-auto overflow-hidden transition-all duration-500 ease-out "
                >
                  <Image src={pfp} alt={"yes"} />
                </motion.div>
                <motion.h1
                  initial={{ opacity: 0, y: -10 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.5 }}
                  viewport={{ once: false }}
                >
                  <motion.h1 className="text-6xl p-6 text-teal-500">
                    <TypeAnimation
                      sequence={[
                        "Meor :)", // Types 'One'
                        1000, // Waits 1s
                        "Syamil!", // Deletes 'One' and types 'Two'
                        1000, // Waits 2s
                        "Meor Syamil.", // Types 'Three' without deleting 'Two'
                        3000,
                      ]}
                      repeat={Infinity}
                    />
                  </motion.h1>
                </motion.h1>
                <h3 className="text-lg font-medium py-4 leading-none">
                  Computer Engineer Graduate + Future Developer/Designer
                </h3>
                <p className="text-gray-300 lg:w-1/3 md:w-1/3 py-4">Hello!</p>
                <p className="text-gray-300 lg:w-1/3 md:w-1/3">
                  I am a recent Computer Engineering graduate from Universiti
                  Teknologi PETRONAS, with a passion for software engineering. I
                  am driven to develop creative solutions to complex problems
                  and am eager to bring my technical skills and passion for
                  innovation to the table. My experience and education have
                  equipped me with the ability to develop robust and efficient
                  software systems, and I am eager to apply these skills to
                  real-world challenges. My portfolio website showcases some of
                  my past projects and highlights my experience and expertise as
                  a software engineer.
                </p>
                <p className="text-gray-300 lg:w-1/3 md:w-1/3 py-4">
                  Take a look to see what I can bring to your team.
                </p>
              </div>
              <motion.div
                initial={{ y: -30, opacity: 0 }}
                whileInView={{ y: 0, opacity: 1 }}
                transition={{ duration: 0.5 }}
                viewport={{ once: true }}
              >
                <div className="text-5xl flex justify-center py-6 gap-6 ">
                  <a
                    target="_blank"
                    href="https://github.com/w30r"
                    rel="noreferrer"
                  >
                    <AiFillGithub />
                  </a>
                  <a
                    target="_blank"
                    href="https://twitter.com/fathihilmi_"
                    rel="noreferrer"
                  >
                    <AiFillTwitterCircle />
                  </a>
                  <a
                    target="_blank"
                    href="https://www.linkedin.com/in/meor-syamil-59935a153/"
                    rel="noreferrer"
                  >
                    <AiFillLinkedin />
                  </a>
                </div>
              </motion.div>
            </section>

            <section>
              <motion.div
                initial={{ opacity: 0 }}
                whileInView={{ opacity: 1 }}
                transition={{ duration: 0.5 }}
                viewport={{ once: false }}
              >
                <div>
                  <div className="whitespace-no-wrap">
                    <h3 className="text-center text-3xl py-1 font-semibold my-4">
                      My Experiences 🛠
                    </h3>
                  </div>
                  <div>
                    <Card />
                  </div>
                </div>
              </motion.div>
            </section>

            <section>
              <motion.div
                initial={{ opacity: 0 }}
                whileInView={{ opacity: 1 }}
                transition={{ duration: 0.5 }}
                viewport={{ once: false }}
              >
                <div className="whitespace-no-wrap">
                  <h3 className="text-center text-3xl py-1 font-semibold my-4">
                    Award(s) + Achievements 🥇
                  </h3>
                </div>

                <div>
                  <AwardCard />
                </div>
              </motion.div>
            </section>
          </main>
        </html>
      </div>
    </motion.div>
  );
}
