import Head from "next/head";
import { Inter } from "@next/font/google";
import { AiFillThunderbolt } from "react-icons/ai";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub,
} from "react-icons/ai";
import pfp from "../../public/pfp.png";
import Image from "next/image";
import Card from "./components/card";
import AwardCard from "./components/awardcard";
import { motion } from "framer-motion";

export default function Home() {
  return (
    <motion.div
      initial={{ opacity: 0 }}
      transition={{ duration: 2 }}
      animate={{ opacity: 1 }}
    >
      <div>
        <html className="scroll-smooth">
          <Head>
            <title>Meor's Web Portfolio</title>
            <meta name="description" content="Generated by create next app" />
            <meta
              name="viewport"
              content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <main className=" bg-black px-10">
            <section className="min-h-screen">
              <nav className="py-10 mb-12 flex justify-between">
                <h1 className="text-xl p-10 font-burtons">developedbymeor</h1>
                <ul className="flex items-center">
                  <li>
                    <AiFillThunderbolt className=" cursor-pointer text-2xl" />
                  </li>
                  <li className="px-1">
                    <motion.div
                      whileHover={{ scale: 1.1 }}
                      onHoverStart={(e) => {}}
                      onHoverEnd={(e) => {}}
                    >
                      <a
                        className="bg-size-200 bg-pos-0 hover:bg-pos-100 transition-all duration-500 bg-gradient-to-tl from-blue-500 to-teal-500 px-4 py-2 rounded-md "
                        href="/README.md"
                      >
                        Resume
                      </a>
                    </motion.div>
                  </li>
                </ul>
              </nav>
              <div className="text-center flex items-center flex-col ">
                <motion.h1
                  initial={{ opacity: 0, y: -10 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.5 }}
                  viewport={{ once: false }}
                >
                  <h2 className="text-6xl py-6 text-teal-500 font-semibold">
                    Meor Syamil
                  </h2>
                </motion.h1>
                <h3 className="text-lg font-medium py-4 leading-none">
                  Computer Engineer Graduate + Future Developer/Designer
                </h3>
                <p className="text-gray-300 lg:w-1/3 md:w-1/3 py-4">Hello!</p>
                <p className="text-gray-300 lg:w-1/3 md:w-1/3">
                  I am a recent Computer Engineering graduate from Universiti
                  Teknologi PETRONAS, with a passion for software engineering. I
                  am driven to develop creative solutions to complex problems
                  and am eager to bring my technical skills and passion for
                  innovation to the table. My experience and education have
                  equipped me with the ability to develop robust and efficient
                  software systems, and I am eager to apply these skills to
                  real-world challenges. My portfolio website showcases some of
                  my past projects and highlights my experience and expertise as
                  a software engineer.
                </p>
                <p className="text-gray-300 lg:w-1/3 md:w-1/3 py-4">
                  Take a look to see what I can bring to your team.
                </p>
              </div>
              <motion.div
                initial={{ y: -30, opacity: 0 }}
                whileInView={{ y: 0, opacity: 1 }}
                transition={{ duration: 0.5 }}
                viewport={{ once: true }}
              >
                <div className="text-5xl flex justify-center py-6 gap-6 ">
                  <AiFillTwitterCircle />
                  <AiFillGithub />
                  <AiFillLinkedin />
                </div>
              </motion.div>
              <motion.div
                initial={{ x: -30, opacity: 0 }}
                whileInView={{ x: 0, opacity: 1 }}
                transition={{ duration: 0.5 }}
                viewport={{ once: false }}
                whileHover={{ scale: 1.05 }}
              >
                <div className="mb-24 relative bg-gradient-to-b via-cyan-900 from-teal-600 to-black rounded-full w-60 h-60 mt-12 mx-auto overflow-hidden transition-all duration-500 ease-out ">
                  <Image src={pfp} />
                </div>
              </motion.div>
            </section>

            <section>
              <motion.div
                initial={{ opacity: 0 }}
                whileInView={{ opacity: 1 }}
                transition={{ duration: 0.5 }}
                viewport={{ once: false }}
              >
                <div>
                  <div className="whitespace-no-wrap">
                    <h3 className="text-center text-3xl py-1 font-semibold my-4">
                      My Experiences 🛠
                    </h3>
                  </div>
                  <div>
                    <Card />
                  </div>
                </div>
              </motion.div>
            </section>

            <section>
              <motion.div
                initial={{ opacity: 0 }}
                whileInView={{ opacity: 1 }}
                transition={{ duration: 0.5 }}
                viewport={{ once: false }}
              >
                <div className="whitespace-no-wrap">
                  <h3 className="text-center text-3xl py-1 font-semibold my-4">
                    Award(s) + Achievements 🥇
                  </h3>
                </div>

                <div>
                  <AwardCard />
                </div>
              </motion.div>
            </section>
          </main>
        </html>
      </div>
    </motion.div>
  );
}
